name: ServerRestartMessage
version: '0.1'
main: yuuyuu4621.net.serverrestartmessage.ServerRestartMessage
api-version: '1.20'

default-permission: &none あなたには権限がありません！ (You don't have permission!)
commands:
  restartmessage:
    description: サーバーの再起動時にメッセージを送信します。
    permission: restartmessage.message
    permission-message: *none
  fly:
    description: チャット欄でカウントダウンを行います。
    permission: restartmessage.countdown
    permission-message: *none
  kwhitelist:
    description: ホワイトリストを有効化し、OP権限を持っていない全てのプレイヤーをキックします。
    permission: restartmessage.kwhitelist
    permission-message: *none